version: '3'

services:
  oracle_digital_db:
    container_name: oracle_digital_db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: nur_2308
      POSTGRES_DB: oracle
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"

  oracle_app:
    container_name: oracle_app
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/OracleDigital/manage.py makemigrations &&
        python /usr/src/OracleDigital/manage.py migrate --noinput &&
        python /usr/src/OracleDigital/manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/usr/src/OracleDigital
    ports:
      - "8000:8000"
    depends_on:
      - oracle_digital_db

  oracle_worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A OracleDigital worker --loglevel=info --beat
    volumes:
      - .:/usr/src/OracleDigital
    depends_on:
      - oracle_digital_db
    links:
      - redis

  oracle_crontab:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/OracleDigital/manage.py crontab add"
    volumes:
      - .:/usr/src/OracleDigital
    depends_on:
      - oracle_digital_db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
