# Generated by Django 4.2.2 on 2023-06-27 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(
                blank=True, null=True, related_query_name="classes", to="school.student"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="teachers_classroom",
                to="school.class",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="classrooms",
            field=models.ManyToManyField(
                blank=True, null=True, related_query_name="schools", to="school.class"
            ),
        ),
    ]
