# Generated by Django 4.2.2 on 2023-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_class_student_class_teacher_teacher_classroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(
                blank=True, related_query_name="classes", to="school.student"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="classrooms",
            field=models.ManyToManyField(
                blank=True, related_query_name="schools", to="school.class"
            ),
        ),
    ]
