# Generated by Django 4.2.2 on 2023-07-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_teacher_groups_alter_teacher_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
